import 'dart:io';

import 'package:camera/camera.dart';
import 'package:collectiq_ai/core/errors/scanner_exception.dart';
import 'package:collectiq_ai/core/network/network_exceptions.dart';
import 'package:collectiq_ai/features/ai/domain/entities/recognition_result.dart';
import 'package:collectiq_ai/features/ai/domain/repositories/recognition_repository.dart';
import 'package:collectiq_ai/features/ai/services/ai_providers.dart';
import 'package:collectiq_ai/features/portfolio/presentation/controllers/portfolio_controller.dart';
import 'package:collectiq_ai/features/scanner/domain/entities/scan_result.dart';
import 'package:collectiq_ai/features/scanner/services/camera_service.dart';
import 'package:collectiq_ai/features/scanner/services/gallery_service.dart';
import 'package:collectiq_ai/features/scanner/services/scanner_providers.dart';
import 'package:collectiq_ai/shared/domain/entities/collectible_item.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Immutable presentation state for the scanner workflow.
class ScannerState {
  /// Creates scanner state.
  const ScannerState({
    this.isCameraInitialized = false,
    this.isLoading = false,
    this.selectedImage,
    this.selectedImagePath,
    this.selectedItemTitle,
    this.selectedItemStatus,
    this.scanResult,
    this.aiRecommendation,
    this.errorMessage,
  });

  /// Whether the camera has been initialized for use.
  final bool isCameraInitialized;

  /// Whether the scanner workflow is currently loading.
  final bool isLoading;

  /// Image selected from camera or gallery.
  final XFile? selectedImage;

  /// Local file path for the selected scanner image.
  final String? selectedImagePath;

  /// Display title for the currently selected scan preview item.
  final String? selectedItemTitle;

  /// Display status for the currently selected scan preview item.
  final String? selectedItemStatus;

  /// Latest scan result, once AI scanning is implemented.
  final ScanResult? scanResult;

  /// Recommendation generated by the temporary AI result flow.
  final String? aiRecommendation;

  /// Latest user-safe scanner error message.
  final String? errorMessage;

  /// Creates a copy of the current scanner state.
  ScannerState copyWith({
    bool? isCameraInitialized,
    bool? isLoading,
    XFile? selectedImage,
    String? selectedImagePath,
    String? selectedItemTitle,
    String? selectedItemStatus,
    ScanResult? scanResult,
    String? aiRecommendation,
    String? errorMessage,
    bool clearSelectedImage = false,
    bool clearSelectedImagePath = false,
    bool clearSelectedItemTitle = false,
    bool clearSelectedItemStatus = false,
    bool clearScanResult = false,
    bool clearAiRecommendation = false,
    bool clearErrorMessage = false,
  }) {
    return ScannerState(
      isCameraInitialized: isCameraInitialized ?? this.isCameraInitialized,
      isLoading: isLoading ?? this.isLoading,
      selectedImage: clearSelectedImage
          ? null
          : selectedImage ?? this.selectedImage,
      selectedImagePath: clearSelectedImagePath
          ? null
          : selectedImagePath ?? this.selectedImagePath,
      selectedItemTitle: clearSelectedItemTitle
          ? null
          : selectedItemTitle ?? this.selectedItemTitle,
      selectedItemStatus: clearSelectedItemStatus
          ? null
          : selectedItemStatus ?? this.selectedItemStatus,
      scanResult: clearScanResult ? null : scanResult ?? this.scanResult,
      aiRecommendation: clearAiRecommendation
          ? null
          : aiRecommendation ?? this.aiRecommendation,
      errorMessage: clearErrorMessage
          ? null
          : errorMessage ?? this.errorMessage,
    );
  }
}

/// Controller that coordinates scanner presentation state and workflow events.
class ScannerController extends Notifier<ScannerState> {
  /// Camera service dependency.
  late final CameraService _cameraService;

  /// Gallery service dependency.
  late final GalleryService _galleryService;

  /// AI recognition repository dependency.
  late final RecognitionRepository _recognitionRepository;

  @override
  ScannerState build() {
    _cameraService = ref.watch(cameraServiceProvider);
    _galleryService = ref.watch(galleryServiceProvider);
    _recognitionRepository = ref.watch(recognitionRepositoryProvider);
    return const ScannerState();
  }

  /// Initializes camera state for the scanner screen.
  Future<void> initializeCamera() async {
    state = state.copyWith(
      isLoading: true,
      clearScanResult: true,
      clearAiRecommendation: true,
      clearErrorMessage: true,
    );
    await _cameraService.initializeCamera();
    state = state.copyWith(isCameraInitialized: true, isLoading: false);
  }

  /// Requests camera permissions for future capture flows.
  Future<bool> requestCameraPermissions() {
    return _cameraService.requestPermissions();
  }

  /// Opens the selected camera.
  Future<void> openCamera() {
    return _cameraService.openCamera();
  }

  /// Captures an image and stores it as the selected scanner image.
  Future<void> captureImage() async {
    state = state.copyWith(isLoading: true, clearErrorMessage: true);
    final image = await _cameraService.captureImage();
    state = state.copyWith(
      selectedImage: image,
      selectedImagePath: image.path,
      selectedItemTitle: 'Captured image',
      selectedItemStatus: 'Ready for AI analysis',
      isLoading: false,
    );
  }

  /// Opens the camera capture page and stores the captured image path.
  Future<void> startCameraScan(BuildContext context) async {
    state = state.copyWith(isLoading: true, clearErrorMessage: true);
    try {
      final capturedImage = await _cameraService.pickImageFromCamera();
      if (capturedImage == null || capturedImage.path.isEmpty) {
        state = state.copyWith(
          isLoading: false,
          errorMessage: 'Camera capture cancelled.',
        );
        return;
      }

      final image = await _cameraService.persistCapturedImage(capturedImage);
      final selectedImagePath = _displayPathFor(image);
      debugPrint(
        '[Scanner] selectedImagePath after camera capture: '
        '$selectedImagePath',
      );
      state = state.copyWith(
        selectedImage: image,
        selectedImagePath: selectedImagePath,
        selectedItemTitle: 'Captured image',
        selectedItemStatus: 'Ready for AI analysis',
        isLoading: false,
        clearScanResult: true,
        clearAiRecommendation: true,
      );
    } on ScannerException catch (error) {
      state = state.copyWith(
        isLoading: false,
        errorMessage: error.message,
        clearSelectedImage: true,
        clearSelectedImagePath: true,
        clearSelectedItemTitle: true,
        clearSelectedItemStatus: true,
        clearScanResult: true,
        clearAiRecommendation: true,
      );
    } on Exception {
      state = state.copyWith(
        isLoading: false,
        errorMessage: 'Unable to open the camera.',
      );
    }
  }

  /// Creates a sample selected scan for development and UI testing.
  void useSampleScan() {
    state = state.copyWith(
      selectedImagePath: 'sample://sports-card',
      selectedItemTitle: 'Sample Sports Card',
      selectedItemStatus: 'Ready for AI analysis',
      clearSelectedImage: true,
      clearScanResult: true,
      clearAiRecommendation: true,
      clearErrorMessage: true,
    );
  }

  /// Opens the gallery and stores a validated selected image.
  Future<void> pickImageFromGallery() async {
    state = state.copyWith(isLoading: true, clearErrorMessage: true);
    try {
      final image = await _galleryService.pickImage();
      if (image == null) {
        state = state.copyWith(isLoading: false);
        return;
      }

      await _galleryService.validateImage(image);
      final selectedImagePath = _displayPathFor(image);
      debugPrint('[Scanner] selected image path: $selectedImagePath');
      state = state.copyWith(
        selectedImage: image,
        selectedImagePath: selectedImagePath,
        selectedItemTitle: 'Gallery image',
        selectedItemStatus: 'Ready for AI analysis',
        isLoading: false,
        clearScanResult: true,
        clearAiRecommendation: true,
      );
    } on ScannerException catch (error) {
      state = state.copyWith(
        isLoading: false,
        errorMessage: error.message,
        clearSelectedImage: true,
        clearSelectedImagePath: true,
        clearSelectedItemTitle: true,
        clearSelectedItemStatus: true,
        clearScanResult: true,
        clearAiRecommendation: true,
      );
    } on Exception {
      state = state.copyWith(
        isLoading: false,
        errorMessage: 'Something went wrong. Please try again.',
      );
    }
  }

  /// Runs AI analysis for the selected scan preview.
  Future<void> analyzeWithAi() async {
    final selectedImagePath = state.selectedImagePath;
    if (selectedImagePath == null) {
      return;
    }

    state = state.copyWith(isLoading: true, clearErrorMessage: true);
    try {
      final recognition = selectedImagePath.startsWith('sample://')
          ? _sampleRecognitionResult()
          : await _recognizeSelectedImage();
      final thumbnail = _portfolioImagePathFor(
        selectedImagePath: selectedImagePath,
        recognitionImageUrl: recognition.imageUrl,
      );
      debugPrint('[Scanner] ScanResult.thumbnail: $thumbnail');
      state = state.copyWith(
        isLoading: false,
        scanResult: ScanResult(
          id: 'scan-${DateTime.now().millisecondsSinceEpoch}',
          title: recognition.title,
          category: recognition.category,
          estimatedValue: recognition.estimatedValue,
          confidence: recognition.confidence,
          condition: recognition.condition,
          thumbnail: thumbnail,
          scanDate: DateTime.now(),
        ),
        aiRecommendation: recognition.recommendation,
      );
    } on NetworkException catch (error) {
      state = state.copyWith(
        isLoading: false,
        errorMessage: _messageForNetworkError(error),
        clearScanResult: true,
        clearAiRecommendation: true,
      );
    } on Exception {
      state = state.copyWith(
        isLoading: false,
        errorMessage: 'Something went wrong. Please try again.',
        clearScanResult: true,
        clearAiRecommendation: true,
      );
    }
  }

  /// Saves the latest scan result to the in-memory portfolio.
  Future<void> saveScanResultToPortfolio() async {
    final result = state.scanResult;
    if (result == null) {
      return;
    }

    final item = CollectibleItem(
      id: result.id,
      title: result.title,
      category: result.category,
      estimatedValue: result.estimatedValue,
      confidence: result.confidence,
      condition: result.condition,
      recommendation:
          state.aiRecommendation ?? 'Consider grading before selling.',
      imagePath: result.thumbnail,
      createdAt: DateTime.now(),
    );

    debugPrint(
      '[Scanner] CollectibleItem.imagePath before save: '
      '${item.imagePath}',
    );
    debugPrint(
      '[Scanner] image file exists before save: '
      '${await _localFileExists(item.imagePath)}',
    );
    await ref.read(portfolioControllerProvider.notifier).saveItem(item);
  }

  /// Switches between available cameras.
  Future<void> switchCameras() {
    return _cameraService.switchCameras();
  }

  /// Sets camera flash mode.
  Future<void> setFlashMode(FlashMode mode) {
    return _cameraService.setFlashMode(mode);
  }

  /// Disposes active camera resources.
  Future<void> disposeCamera() {
    return _cameraService.disposeCamera();
  }

  Future<RecognitionResult> _recognizeSelectedImage() {
    final image = state.selectedImage;
    if (image == null) {
      throw StateError('No image selected for analysis.');
    }

    return _recognitionRepository.recognizeCollectible(image);
  }

  String _displayPathFor(XFile image) {
    if (image.path.isNotEmpty) {
      return image.path;
    }

    return image.name.isEmpty ? 'selected-image' : image.name;
  }

  String _portfolioImagePathFor({
    required String selectedImagePath,
    required String? recognitionImageUrl,
  }) {
    if (_isUsableSelectedImagePath(selectedImagePath)) {
      return selectedImagePath;
    }

    final normalizedRecognitionImageUrl = recognitionImageUrl?.trim();
    if (normalizedRecognitionImageUrl != null &&
        normalizedRecognitionImageUrl.isNotEmpty) {
      return normalizedRecognitionImageUrl;
    }

    return selectedImagePath;
  }

  bool _isUsableSelectedImagePath(String imagePath) {
    final normalizedPath = imagePath.trim();
    if (normalizedPath.isEmpty || normalizedPath == 'selected-image') {
      return false;
    }

    return !normalizedPath.startsWith('sample://');
  }

  Future<bool> _localFileExists(String imagePath) async {
    final normalizedPath = imagePath.trim();
    if (normalizedPath.isEmpty ||
        normalizedPath.startsWith('sample://') ||
        normalizedPath.startsWith('http://') ||
        normalizedPath.startsWith('https://') ||
        normalizedPath.startsWith('assets/')) {
      return false;
    }

    return File(normalizedPath).exists();
  }

  String _messageForNetworkError(NetworkException error) {
    return switch (error.statusCode) {
      413 => 'Image is too large. Please choose an image under 10MB.',
      415 => 'Please select a PNG, JPG, or JPEG image.',
      _ => 'Unable to connect to AI service.',
    };
  }

  RecognitionResult _sampleRecognitionResult() {
    return const RecognitionResult(
      success: true,
      filename: null,
      imageUrl: 'sample://sports-card',
      title: '1999 Pokémon Charizard',
      category: 'Trading Card',
      confidence: 0.94,
      description: 'Sample scanner result.',
      estimatedValue: 1850,
      condition: 'Near Mint',
      recommendation: 'Consider grading before selling.',
    );
  }
}

/// Provides scanner presentation state and workflow coordination.
final scannerControllerProvider =
    NotifierProvider<ScannerController, ScannerState>(ScannerController.new);
